[package]
name = "lars"
version = "0.0.0"
authors = [
	"Tom Schouten <tom@zwizwa.be>",
]

description = "Logic Analyzer and Protocol Decoder library"
homepage = "https://github.com/zwizwa/lars"
repository = "https://github.com/zwizwa/lars"
license = "MIT"

[lib]
name = "la"
path = "src/lib.rs"


[[bin]]
name = "uart"
path = "examples/uart.rs"

[[bin]]
name = "diff"
path = "examples/diff.rs"

[[bin]]
name = "slip"
path = "examples/slip.rs"

[[bin]]
name = "ice40"
path = "examples/ice40.rs"

